### PR TITLE
connectors: Add support for screw terminals

### PR DESCRIPTION
**Pull request by dbrgn**
Library PR: https://github.com/LibrePCB-Libraries/LibrePCB_Connectors.lplib/pull/13

Add screw terminal symbols / components.

For inspiration, I looked at the KiCAD symbol:

screenshot-20220716-221300

This looks quite nice, but we cannot replicate it because the pin labels are not yet movable.

This leaves us with two options:

**A: Move the screw circle to the right, re-using the line**

screenshot-20220716-224852

The circle is very small though and does not really resemble a screw.

**B: Make the symbol wider**

screenshot-20220716-224701

By making the symbol wider, we have room for the screw on the left side.

I chose this approach. To ensure consistent alignment with other pin headers/sockets, the rectangle expands to the left, it is not centered. This means that you can replace a pin socket with a screw terminal without the wires moving in the schematic.

Here's the final symbol:

screenshot-20220716-232200 screenshot-20220716-232240

### CODE REVIEW

**Comment by ubruhin** [comment]
Nice! But why not simply make the line shorter?

image

Then the outline is the same as for the other connectors. And with LibrePCB 0.2 we could then either move the text very slightly to the right or out of the symbol to improve the look a bit (although I'm not sure about moving it of the symbol since then it would be inconsistent to all the other symbols...)

**Comment by dbrgn** [comment]
Hmm, I think that should work as well. I'll try to fix it.

By the way, any preferences regarding terminology, screw terminal vs terminal block?

**Comment by ubruhin** [comment]
I rebased the branch and slightly adjusted the symbol layout, now making use of the LibrePCB 1.0 feature of specifying a custom symbol text position :muscle: 

image

From my point of view, this is now ready to merge.

**Comment by dbrgn** [comment]
Awesome, looking great now! I'll check it again, and will then update the associated library PR.

**Review by ubruhin — APPROVED** [review]

**Pull request merged**
