### PR TITLE
added download scripts and csv files

### PR DESCRIPTION
**Pull request by ouabache**

### CODE REVIEW

**Comment by dbrgn** [comment]
Thanks! I looked through the scripts and the approach makes sense. Needs some cleanup, but I think we can use this.

However, all the scripts together are quite huge, so I don't think we should keep them in this repository. I'll cherry-pick your commits and will create a separate repository for the data files.

**Comment by ouabache** [comment]
So each library has its own repository. The source csv files should go in
the same repo.

**Comment by dbrgn** [comment]
No, I don't think that we should mix LibrePCB libraries and raw data files.

I created https://github.com/LibrePCB/stm32-pinout/ for now. The goal for that repository is to hold only the scripts and data files, nothing related to generating LibrePCB parts. The parts generator itself will remain in this repository. That way, other projects might benefit from the data files as well.

My current work is being done here: https://github.com/LibrePCB/stm32-pinout/pull/1 I'll also push the data files soon, CubeMX is still exporting :slightly_smiling_face: Among other things I write pinouts to `data/<reference>.pinout.csv` and other metainformation to `data/<reference>.info.json`.

Some feedback about your Python script that might be helpful (since IIRC you're still learning Python):

- I used `csv.DictReader` to parse the CSV file, then you can access rows by name instead of by index
- You can skip rows in a file by using `f.readline()` and discarding the result
- If you use [context managers](https://book.pythontips.com/en/latest/context_managers.html) when opening files, you don't need to explicitly close them

**Comment by dbrgn** [comment]
@ouabache did you also get a lot of these warnings when exporting the pinout files?

2020-02-13-232656_1636x644_scrot

**Comment by dbrgn** [comment]
The CubeMX GUI also cannot load this MCU, so I guess it's simply missing from the database :slightly_smiling_face:

**Comment by dbrgn** [comment]
Ok, so I'll close this in favor of https://github.com/LibrePCB/stm32-pinout. I'll continue with #80.

@ouabache thanks for your work!

**Comment by ouabache** [comment]
Yes, About 2 dozen or so did not have pinout files.

I only downloaded the ones marked "Active" so I was surprised at this.
Maybe I should download everything and store the status. If its obsolete or
planned then we build the part but mark it as not recommended for new
designs.

We will need to update this on a regular basis to pick up any new parts and
mark any obsolete parts as ST changes things. That's why I prefer putting
everything in one repo to make life simpler for future librarians

**Comment by ouabache** [comment]
Thanks for the feedback.

I am beginning to like python

**Pull request closed without merging**
