### PR TITLE
Rework DIP package generator

### LINKED ISSUE #32: Rename DIP packages
According to IPC, the name should be:

img

Make sure to retain the UUIDs and to bump the version.

### PR DESCRIPTION
**Pull request by dbrgn**
This is a total rework of DIP package generator. Another one of those PRs where I thought "let me quickly do those changes", but then I spent a total of 10-15 hours on it :sweat_smile: (Mostly research)

- Updated dimensions (based on JEDEC and real-world package sizes)
- Deprecated a few DIP packages:  DIP-36, DIP-48, DIP-52 and DIP-64 (since they have practically no real-world use, and if they do the packages sometimes deviate from the standard sizes, so generic packages shouldn't be used)
- New silkscreen conforming to IPC7351C recommendations
- Use lead span for pad x-offset, not package width
- Ported parts of the generator to the new entities wrapper types

Version has been bumped to v0.2.0.

This PR also includes the changes by @ouabache in #73. Fixes #32.

I'll create a PR against the base library for easier discussion.

### CODE REVIEW

**Comment by ubruhin** [comment]
Generally very nice rework & documentation! :rocket: 

I didn't review everything in detail yet, but my comments so far:

- The terms "lead span" and "body width" are used misleading IMHO. In contrast to SMT packages where lead span usually means the distance between the *outer* edges of the leads, for THT packages it usually means the distance between the *center* of the leads. In both cases this is the number which is relevant for designing the footprint - for THT packages, only the pad distance is relevant, not the outer distance between the leads.
  - Therefore, the package name (e.g. `DIP787W55P254L965H533Q8`) is very confusing because the "787" is not a well-known DIP lead span. See for example [here](https://www.pcb-3d.com/models/dip762w46p254l927h533q8p_jedec_ms-001ba/) that they call it `DIP762...` for a nominal lead span of 7.62mm. Thus I'd highly recommend to adjust our package name as well to contain the *nominal* lead span, not the *outer* lead span.
  - In the description, I'd also adjust change the "Lead span:" to its *nominal* value.
  - The "Body width:" value should be smaller than the nominal lead span. I think here it's fine to just define some number by ourselves since this value is not really relevant. However, a reasonable value would avoid the body to extend up to the center of the pads, which would actually mean that the leads need to be bent towards the package center (which is not true of course):
    image
- Maybe the outline & documentation polygons could be improved a bit? For example by using the IPC recommended pin-1 marking instead of a dot, and by removing the top line crossing the arc, to keep the gap due to the arc visible even after assembly?
  - Current look: 
image
  - Idea: 
image
  Optionally we could even keep the pin-1 dot, but move it to the documentation layer to see it in an assembly drawing :thinking: 
  However, of course these polygon changes are not that important, it's just an idea :see_no_evil: 

If you agree on these changes but don't have the time to implement it, maybe we could do it the same way as for the LED generator that I implement the changes in a separate PR?

**Comment by ubruhin** [comment]
@dbrgn may I rebase this branch and apply the suggestions from https://github.com/LibrePCB/librepcb-parts-generator/pull/75#issuecomment-1233027784? Since this is almost ready it would be nice to finally get it merged :)

**Comment by dbrgn** [comment]
Sorry, I forgot about this PR... Sure, your suggestions sound reasonable, go ahead 🙂

**Comment by ubruhin** [comment]
Alright, I rebased and added two commits with these changes:

- Update to file format v1
- Change lead span from the outer values to the nominal values 7.62mm & 15.24mm.
- Reduce body width by 0.4mm on each side.
- Merge notch polygon into top silkscreen polygon.
- Extend top silkscreen polygon over pin-1.
- Move pin-1 dot to documentation layer and move to the inner of the body.
- Add a package outline polygon.
- Reduce text to body distance from 0.8mm to 0.6mm.
- Add an approval for the missing 3D models.

Result:

image

image

**Comment by dbrgn** [comment]
🎉

**Pull request merged**
