### PR TITLE
DO: Fix warnings & generate 3D models 

### PR DESCRIPTION
**Pull request by ubruhin**
Fix library check warnings:

- Specify assembly type
- Specify pad functions
- Add package outline polygon

Generate 3D models, for both the polarized and non-polarized packages:

image

### CODE REVIEW

**Comment by ubruhin** [comment]
Hmm CI is broken, probably caused by the fact that it installs not numpy 2.0.0 while the last successful CI run was with numpy 1.xx (depending on Python version). Numpy seems to be an indirect dependency of CadQuery:

```
Collecting numpy>=1.20.0 (from nptyping==2.0.1->cadquery==2.3.1->librepcb-parts-generator==0.1.0)
```

@rnestler @dbrgn any suggestion how to fix this? Adding `numpy<2` as a dependency? And can we pin all dependency versions?

**Comment by dbrgn** [comment]
I _think_ you could just add it to the dependencies in pyproject.toml, but don't have a lot of experience with that format yet... Maybe @rnestler knows more.

**Comment by ubruhin** [comment]
Rebased (fixes CI) and library PR opened: https://github.com/LibrePCB-Libraries/LibrePCB_Base.lplib/pull/139

So it should be ready now.

**Comment by ubruhin** [comment]
Library PR merged, thus also merging this.

**Pull request merged**
