### PR TITLE
README: Add some docs

### PR DESCRIPTION
**Pull request by dbrgn**
Document concepts like UUID caching and the entity classes.

### CODE REVIEW

**Comment by dbrgn** [comment]
Good point. In CI we use 3.5/3.6/3.7 (and I'm pretty sure 3.4 does not support all type annotations), so I added 3.5+ to the README.

The requirements are only required for testing and type checking, I added a note about that as well.

**Comment by rnestler** [comment]
> Good point. In CI we use 3.5/3.6/3.7 (and I'm pretty sure 3.4 does not support all type annotations), so I added 3.5+ to the README.

I would even love to ditch 3.5 as well, since it also doesn't support certain type annotations and needs workarounds. Ubuntu LTS has 3.6 btw. :slightly_smiling_face:

**Comment by dbrgn** [comment]
Would be fine with me.

**Comment by rnestler** [comment]
> Would be fine with me. You mean things like variable annotations with # type: comments, right?

Yes, for example.

**Pull request merged**
