### PR TITLE
TSSOP part generator

### LINKED ISSUE #25: Generate TSSOP
Can be integrated into `generate_so.py`

### PR DESCRIPTION
**Pull request by dbrgn**
Generate TSSOP parts based on JEDEC MO-153.

Fixes #25.

### CODE REVIEW

**Comment by dbrgn** [comment]
Ready for review.

**Comment by dbrgn** [comment]
Generated parts can be reviewed here: https://github.com/LibrePCB-Libraries/LibrePCB_Base.lplib/pull/33 Should be merged first.

**Comment by rnestler** [comment]
The refactoring looks nice, but I can't really comment on the generated TSSOP packages.
Maybe it would be easier to merge the refactoring first, which results in the same output for the existing packages?

**Comment by dbrgn** [comment]
Ugh that rebase sucks because of the new indentation...

**Comment by dbrgn** [comment]
...but kdiff3 is nice :)

mergetool

**Comment by dbrgn** [comment]
Rebased on top of #51.

**Pull request merged**
